micronaut:
  application:
    name: foosball
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api/schema/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /api/redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /api/rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api/swagger-ui/**

---
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
jpa:
  default:
    entity-scan:
      packages: com.thecodesmith.foos.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
