micronaut:
  application:
    name: foosball

---
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
jpa:
  default:
    entity-scan:
      packages: com.thecodesmith.foos.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
